print(getwd())
setwd("C:/Users/dilll/OneDrive/Documents/1a")
data1 <- read.csv("input.csv")
data1 <- read.csv("input.csv")
print(data1)
data2 <- read.csv("input.csv")
print(is.data.frame(data2))
print(ncol(data2))
print(nrow(data2))
data3 <- read.csv("input.csv")
sal <- max(data3$salary)
print(sal)
data4 <- read.csv("input.csv")
sal <- max(data4$salary)
retval <- subset(data4, salary == max(salary))
print(retval)
data5<- read.csv("input.csv")
retval <- subset( data5, dept == "IT")
print(retval)
data6 <- read.csv("input.csv")
info <- subset(data6, salary > 600 & dept == "IT")
print(info)
data7 <- read.csv("input.csv")
retval <- subset(data7, as.Date(start_date) > as.Date("2014-01-01"))
print(retval)
data8 <- read.csv("input.csv")
retval <- subset(data8, as.Date(start_date) > as.Date("2014-01-01"))
write.csv(retval,"output.csv")
newdata1 <- read.csv("output.csv")
print(newdata1)
data9 <- read.csv("input.csv")
retval <- subset(data9, as.Date(start_date) > as.Date("2014-01-01"))
write.csv(retval,"output.csv", row.names = FALSE)
newdata2 <- read.csv("output.csv")
print(newdata2)