v1=c(1,2,3)
v2=c(1,2,3)
print("Vector Addition :")
print(v1+v2)
print("Vector Subtraction :")
print(v1-v2)
print("Vector Multiplication ")
print(v1*v2)
print("Vector Division :")
print(v1/v2)