r1=c(1,2,3,4)
r2=c(9,10,11,12)
mat1=matrix(r1,nrow=2,ncol=2,byrow = TRUE)
row.names(mat1)=c("A","B")
colnames(mat1)=c("C","D")
mat2=matrix(r2,nrow=2,ncol=2,byrow = TRUE)
row.names(mat2)=c("A","B")
colnames(mat2)=c("C","D")
print("Scalar multiplication :")
print(mat1*2)
print("Matrix Multiplication :")
print(mat1*mat2)