r1=c(1,2,3,4)
r2=c(9,10,11,12)
mat1=matrix(r1,nrow=2,ncol=2,byrow = TRUE)
row.names(mat1)=c("A","B")
colnames(mat1)=c("C","D")
print("Matrix :")
print(mat1)
print("Transpose of Matrix :")
print(t(mat1))