r1=c(1,2,3,4)
r2=c(9,10,11,12)
mat1=matrix(r1,nrow=2,ncol=2,byrow = TRUE)
row.names(mat1)=c("A","B")
colnames(mat1)=c("C","D")
mat2=matrix(r2,nrow=2,ncol=2,byrow = TRUE)
row.names(mat2)=c("A","B")
colnames(mat2)=c("C","D")
print("Original matrices :")
print(mat1)
print(mat2)
print("Matrices after Cbind :")
print(cbind(mat1,mat2))
print("Matrices after Rbind :")
print(rbind(mat1,mat2))